require('common');

local settings = T{ };
settings["userSettings"] = T{ };
settings["userSettings"]["expBarScaleY"] = 1;
settings["userSettings"]["showGilTracker"] = true;
settings["userSettings"]["partyListBuffScale"] = 1;
settings["userSettings"]["enemyListIconScale"] = 1;
settings["userSettings"]["inventoryTrackerFontOffset"] = 0;
settings["userSettings"]["barRoundness"] = 6;
settings["userSettings"]["showEnemyList"] = true;
settings["userSettings"]["playerBarScaleY"] = 1;
settings["userSettings"]["gilTrackerScale"] = 1;
settings["userSettings"]["playerBarScaleX"] = 1;
settings["userSettings"]["targetBarScaleX"] = 1;
settings["userSettings"]["enemyListScaleY"] = 1;
settings["userSettings"]["partyListTheme"] = 0;
settings["userSettings"]["expBarFontOffset"] = 0;
settings["userSettings"]["expBarScaleX"] = 1;
settings["userSettings"]["enemyListFontScale"] = 1;
settings["userSettings"]["showPartyListWhenSolo"] = false;
settings["userSettings"]["showInventoryTracker"] = true;
settings["userSettings"]["partyListFontOffset"] = 0;
settings["userSettings"]["maxEnemyListEntries"] = 8;
settings["userSettings"]["partyListScaleX"] = 1;
settings["userSettings"]["showPlayerBar"] = true;
settings["userSettings"]["targetBarScaleY"] = 1;
settings["userSettings"]["showExpBar"] = true;
settings["userSettings"]["playerBarFontOffset"] = 0;
settings["userSettings"]["gilTrackerFontOffset"] = 0;
settings["userSettings"]["partyListStatusTheme"] = 0;
settings["userSettings"]["targetBarIconScale"] = 1;
settings["userSettings"]["inventoryTrackerScale"] = 1;
settings["userSettings"]["partyListScaleY"] = 1;
settings["userSettings"]["enemyListScaleX"] = 1;
settings["userSettings"]["showTargetBar"] = true;
settings["userSettings"]["targetBarFontScale"] = 1;
settings["userSettings"]["showTargetBarPercent"] = true;
settings["userSettings"]["showPartyList"] = true;

return settings;
